language: python
os:
  - linux
matrix:
  include:      
    - name: "Python 3.7.3 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS https://docs.travis-ci.com/user/reference/osx/
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
        - pip3 install click
        - pip3 install .
      script: python3 -m pytest
      after_success: python 3 -m codecov
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.2
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        - pip3 install click
        - pip3 install .
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
python:
  - 3.8
  - 3.7
  - 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: giswqs
  password:
    secure: V1KvJ2pUWtmdSA44x14L7TzK6aRaf9ooh2qR5HwWy79A8Zo9SffLlt2dx33MDVuXHBAUozF3QnqTMltz9xB8kyAmzgqgkSGLw1elq5p7R6+DBn6rsg0QgGEidOES4+hzkipDPNhfLCzmcHOjk9jYgUgWWeoclYrakKGrfRv3DeXoJp9bsHn/8/5Pv5eBhqy1LVzqfYgvkaVn6IMNtRLCqtEVfRmXCeXaUDlIm81EtY+tan66CydRhvfhNlWLGntiSnte1ebyeLmDlPNxYUKh6ojcr2pls/lH2eHXvFcIgN4sJntQtZaFECbBebQ6p/AUahH1C/fN+SeHI9ahVRRucymJRKPEv844U1Nwgl9aLBp7LS/2fEOm413a0Lh6Pt34aQu/HXpl6c7JpNcZqfwsWAi51vBoirGG4EghPVxGO0jBpXLqFxfk+VDrEhWP+LYA/5PF26LmR8A5VU40rcYcJ31t7uD9g3ltaeo8w/PvdGJGWhQS45BkBX0Ut2OjmRj7ecWWgZyl9ahS5G4wKXwgfNEzynt52CeqBkFwioVa90HiPJeBCm5ctYgDVSppfN/56jhjL0d8xmXWhEw3kQ/mIfLPTBs/kf9z4qaE7vILp2yE3wRkLOlwv92lqHLFFRtCqXM+3UqAlk5U49JjoWLXhMsREqzm9XQvx1AepcSVMrk=
  on:
    tags: true
    repo: giswqs/geemap
    python: 3.8
